### ISSUE TITLE
Button does not show up for WQ 82266

### ISSUE THREAD

**Issue by hollo6** [p3lim-wow/ExtraQuestButton#103]
**Describe the bug**
Quest item button is not present when doing [Tower Washing Simulator](https://www.wowhead.com/quest=82266/tower-washing-simulator)

**How to reproduce**
Go to WQ area and note the button is not present for the provided quest item.

**What did you expect?**
Button with keybind usable for the quest item.

**Error report**
N/A

**Screenshots**
N/A

**Comment by p3lim** [comment]
I did that quest yesterday and it worked fine for me :shrug:.

**Comment by hollo6** [comment]
I did it thrice and the button never showed up.

**Comment by p3lim** [comment]
Oh they screwed up the data for it since I did it, the distance to the quest is well over 1000 yards away even when in the middle of the quest area.
