### ISSUE TITLE
Button does not show for quest The Midnight Sentry

### ISSUE THREAD

**Issue by hollo6** [p3lim-wow/ExtraQuestButton#104]
**Describe the bug**
Button is not present for "The Midnight Sentry" (larger keyflame) quest (quest ID: 78657).
Quest item is Sentry Flare (item ID: 211073).

**How to reproduce**
Go to quest area, receive quest and note the button does not show up for the quest item.

**What did you expect?**
Quest item usable with the extra button.

**Error report**
No errors.

**Screenshots**
N/A

**Comment by p3lim** [comment]
I'll probably do it later this week and get it fixed then, thanks for letting me know.
