### ISSUE TITLE
Show/use button/keybind for delve extra actions

### ISSUE THREAD

**Issue by hollo6** [p3lim-wow/ExtraQuestButton#106]
**Describe the solution you'd like**
Would be a huge QoL improvement to have extra abilities in delves usable with this button:
- The Waterworks: 469854 Drop Air Totem
- Kriegval's Rest: Drop Candle
and IIRC there were some more similar ones in other delves that I forgot the name of.

**Describe alternatives you've considered**
Doesn't need to be shown in the button, the main thing would be to be able to use these abilities with the extra button bind.

**Comment by p3lim** [comment]
I agree that this would be nice, however in some of these situations you also have an actual extra button (like stomp to get cogs in waterworks).

I'll take a look though.

**Comment by hollo6** [comment]
Thanks! The important ones are just these droppable safe zones where using a keybind and not having to click could easily save your life.

**Comment by p3lim** [comment]
After looking into it I'd say it's better to just create a macro for this;

```
/cancelaura Enchanted Candle
/cancelaura Air Totem
```

Integrating this into EQB without collisions with other things like quests and action buttons, not to mention I'd have to more or less rewrite a lot of the addon and write new code to support more than just quests, just to replace a pretty static macro more pain than it's worth.

**Comment by hollo6** [comment]
Oh... I tried a lot of things like /cast, /use, xyButton:Click() but nothing worked, I never realized these were buffs that can be cancelled... This will work just fine, thank you!
