### ISSUE TITLE
Option to hide the textures

### ISSUE THREAD

**Issue by 2ndHouse** [p3lim-wow/ExtraQuestButton#11]
Using Dominos and currently hide the textures on my extra button. I'm really loving this addon (it's really how Blizzard should handle quest items I think), but the ExtraQuestButton texture gets in the way of parts of my UI. Any chance of getting an option to hide the textures?

For now, is there a couple of lines of code I could comment out to hide the textures? I did a quick search, but were quite a few lines of code with the word texture, so couldn't figure it out.

**Comment by p3lim** [comment]
See #7.
