### ISSUE TITLE
Error when quests complete that involve quest items with icons

### ISSUE THREAD

**Issue by raysmith59** [p3lim-wow/ExtraQuestButton#13]
I'm running the latest version 80000.10, as soon as the quest completes and the quest tracker info changes and removes the icon this error pops up.  Happens every time.  I only started using this add-on yesterday so not sure if something has changed recently but it has never worked for me since I first tried it.

Message: ...terface\AddOns\ExtraQuestButton\ExtraQuestButton-80000.10-Release.lua:44: Usage: GetItemCooldown(itemID)
Time: Fri Jul 27 15:22:16 2018
Count: 1
Stack: ...terface\AddOns\ExtraQuestButton\ExtraQuestButton-80000.10-Release.lua:44: Usage: GetItemCooldown(itemID)

Locals:

**Comment by p3lim** [comment]
If you can, test out the latest update from the master branch here on GitHub, I've done some major work on it recently that hasn't been released yet.
I'm marking this as invalid as I cannot reproduce a similiar issue with the changes I've made.

**Comment by raysmith59** [comment]
Somehow the issue seems to have gone away on its own before I could test the master so it's possible it was some interplay with another add-on that was updated in the meantime.  Based on that I'm going to close this off, if it happens again I'll test the master before doing anything else.
