### ISSUE TITLE
Resizing the button with scroll causes the button to move

### ISSUE THREAD

**Issue by raysmith59** [p3lim-wow/ExtraQuestButton#15]
80000.11-Release

Low priority.  I also noticed that the button size changed when I hid the graphics (or at least the green square size changed), not sure if that's intended or not.

**Comment by p3lim** [comment]
The artwork overlays the button and hides part of its texture, making it seem larger when the artwork is hidden, but it's not really.

**Comment by raysmith59** [comment]
Well, the button moving when resizing was the primary report, I was just wondering if the size thing was a separate issue to be reported.  The moving thing should be legit.

**Comment by p3lim** [comment]
The button moving when resizing is just a side effect of how the button is anchored, which I probably will look into fixing.
