### ISSUE TITLE
EQB button disappeared mid-quest

### ISSUE THREAD

**Issue by raysmith59** [p3lim-wow/ExtraQuestButton#16]
80000.11-Release

While doing the quest Help Those That Cannot Help Themselves (Borean Tundra), the EQB showed up for a few mammoths but at some point just disappeared despite the quest still being active.  I'm not seeing any indication of a problem otherwise.

Reloading the UI brought it back.

EDIT: It disappeared again as I approached the trap, may have happened once I got within range of the trap to actually use the ability.  Reloading usually brought it back but didn't once.  Another time I was able to use the EQB but it disappeared when used but I was already within range to use it.  There may just be something weird about this quest.  I'll follow up if I see anything similar with other quests.

EDIT 2: So far it's just been that one quest, the button was left in a hidden/inactive state when that quest completed and remained hidden for a subsequent quest with a button but when I used the quest tracker button for the action the EQB button came back and has been working normally since, I believe.

**Comment by p3lim** [comment]
Thanks for reporting, I'll take a look at it.

**Comment by p3lim** [comment]
Picked up every quest from the start of the zone + the camp where the quest giver is for this quest and started freeing the calves, wasn't able to reproduce your issue.

**Comment by p3lim** [comment]
Only thing I can think of was that you moved out of the max range hard-coded into EQB (250sqy) from the center of the quest area, which will automatically flag the quest as being out of range.
This is sadly something I _have_ to do to avoid quest items showing up when they are not supposed to.
I've been asking Blizzard for a way to detect the range from the closest _edge_ of a quest area, but that hasn't been implemented yet, nor do I belive it's going to, limiting the ways I have for detecting the range.

**Comment by raysmith59** [comment]
It's possible, it was a decent sized quest area although I'd be surprised if I was over 250yds from the centre.  Still, may have been.  From my perspective as a user I wouldn't object to EQB being active for the quest item for the closest quest to where I'm currently located, maybe with a filter to ensure I'm in the correct zone for it.  My interface won't be typical, though, EQB doesn't share the EAB for me the way it does with the default UI so there's no downside for me to have EQB active even if I'm not in the area.  If I run into the issue again I'll try manually increasing the range to see if that does have an impact and I'll report back, I haven't seen it happen since though.
