### ISSUE TITLE
Quests with EQB button not showing up

### ISSUE THREAD

**Issue by raysmith59** [p3lim-wow/ExtraQuestButton#17]
Not sure how much you care about earlier expansion quests but I'll just add them here as I come across them.

* The Plume of Alystros - Dragonblight - Item is called 'Skytalon Molts'
* Mystery of the Infinite - Dragonblight - 'Hourglass of Eternity'
* Mystery of the Infinite, Redux - Dragonblight - 'Hourglass of Eternity'
* That Which Creates Can Also Destroy - Dragonblight - 'Seeds of Nature's Wrath' (it did come up for Turgid and Overseer)

**Comment by p3lim** [comment]
Did the items not show up with EQB?

**Comment by raysmith59** [comment]
Right, button didn't show up for these ones except for mentioned exceptions.
