### ISSUE TITLE
Rodrigo's Birdseed Biscuit from WQ:Flew the Coop

### ISSUE THREAD

**Issue by Dairyman** [p3lim-wow/ExtraQuestButton#19]
- What version are you using?
80000.13-Release

- Can the issue be reproduced, and if so, how?
The Rodrigo's Birdseed Biscuit#154878 from the World Quest Flew the Coop#49402 does not get a button.

**Comment by Cluuey** [comment]
Right then, I'll try that.
Sorry I didn't check here first.

**Comment by p3lim** [comment]
@Cluuey did it work?

**Comment by Cluuey** [comment]
Just an update for you, the quest was up yesterday and they've changed it to a vehicle interface!
I guess people didn't like having to click the little button in the quest tracking section and then having to choose where to fire.

**Comment by p3lim** [comment]
Cool! Thanks for the update 👍
