### ISSUE TITLE
Refrain from populating the button with unusable items.

### ISSUE THREAD

**Issue by xizar** [p3lim-wow/ExtraQuestButton#2]
I have lower level alts with myriad level 615 items retrieved from Follower missions through the garrisons which are unusable until level 100.

The button cheerily taunts me with the items which I cannot open, causing me to cry.

Please do not let the addon make me cry.

**Comment by Phanx** [comment]
Sounds like Openables or some other addon that gives you a "click to open the clam/box/other thing" button.
