### ISSUE TITLE
This quest doesn't work.

### ISSUE THREAD

**Issue by Cluuey** [p3lim-wow/ExtraQuestButton#20]
Polly Want A Cracker?
https://www.wowhead.com/quest=50164/polly-want-a-cracker

I've tried adding it via quest id and item id but it isn't working, I'm using zone number 895 as that is what WeakAuras tells me the zone is.
I'm not sure what more to try so I'm leaving this note here for you. :-)

**Comment by p3lim** [comment]
Try the latest version from GitHub, I (hopefully) adressed this in #19, but forgot to push a release.
