### ISSUE TITLE
Fix for use alt button

### ISSUE THREAD

**Issue by GennPen** [p3lim-wow/ExtraQuestButton#21]
2nd button doesn't work if use 2 buttons for EXTRAACTIONBUTTON1.

local key = GetBindingKey('EXTRAACTIONBUTTON1')
if(key) then
	self:SetBindingClick(1, key, self, 'LeftButton')
end

Fix:
local key1, key2 = GetBindingKey('EXTRAACTIONBUTTON1')
if(key1) then
	self:SetBindingClick(1, key1, self, 'LeftButton')
end
if(key2) then
	self:SetBindingClick(2, key2, self, 'LeftButton')
end

**Comment by p3lim** [comment]
Thanks for the report and suggested patch.
