### ISSUE TITLE
no tooltip on extra button

### ISSUE THREAD

**Issue by vioray** [p3lim-wow/ExtraQuestButton#23]
- What version are you using?
latest version and in BFA/retail

- Can the issue be reproduced, and if so, how?
mouseover extra button, no tooltip shows up

- If there was an error message, please include it.
- If there is a graphical issue, please include a screenshot (you can drag-n-drop here).

Make sure you check back often until the issue is resolved for any follow-up questions.

**Comment by p3lim** [comment]
I'm unable to reproduce this. Which quest/item was this with? Were you in combat?
