### ISSUE TITLE
Button not showing.

### ISSUE THREAD

**Issue by Cluuey** [p3lim-wow/ExtraQuestButton#27]
**Describe the bug**
I was doing the [Loose Change](https://www.wowhead.com/quest=52230/loose-change) world quest and the button didn't show up.

I tried adding the quest id and item id to the `ItemData.lua` file in the `ns.itemData.questItems` section but it didn't help.
`[52230] = 158226, -- Stormsong Valley, Loose Change`

As you're aware I'm no expert with this stuff but I like to try and solve things if I can, I figure that's better than just complaining.
I may have it in the wrong section but perhaps I need a more accurate area of Stormsong Valley?
Unfortunately the WQ is ending now and I've collected all the coins so my testing time is over.

**Comment by p3lim** [comment]
Confirmed, will see if I can fix this.

**Comment by p3lim** [comment]
Feel free to try out this: https://github.com/p3lim-wow/ExtraQuestButton/suites/1356457848/artifacts/22064290
I'll push a new version later.
