### ISSUE TITLE
Only show zone.

### ISSUE THREAD

**Issue by griddark** [p3lim-wow/ExtraQuestButton#31]
Quests that aren't in your current zone wouldn't display items even if tracked.

**Comment by p3lim** [comment]
This one is a little hard to accomplish, since the information the game gives us through the API is most often incorrect, and is the reason I keep a custom database for certain quests that are completely off or missing the information completely.

I'll take a look and see if there is a way to accomplish this, but no guarantee.

**Comment by p3lim** [comment]
Please give it a test, here's a packager dev version:
https://github.com/p3lim-wow/ExtraQuestButton/suites/1396546592/artifacts/23158308

**Comment by griddark** [comment]
I've installed it and will test tomorrow.

**Comment by griddark** [comment]
The options are awesome and I love you. 

Scale doesn't save. 
Not sure if this is intentional but there is no saving between characters. I have to configure it each time.

**Comment by p3lim** [comment]
Nothing was saving, I forgot to [add the savedvariable](https://github.com/p3lim-wow/ExtraQuestButton/commit/c53e0c7afd7f328a30e623d551c3f18bd6a8f71b), derp.

Try this one:
https://github.com/p3lim-wow/ExtraQuestButton/suites/1401332925/artifacts/23286780

**Comment by griddark** [comment]
I just completed a world quest and it's kept Raal's hexing stick on screen. This is the quest https://www.wowhead.com/quest=51497/hex-education 
I logged out and back in, and the size/location stayed, but the empty icon showed up.

Let me know if you want me to use bug grabber.

**Comment by p3lim** [comment]
I'll take a look at it once I see a world quest with an item, thanks for testing.

**Comment by griddark** [comment]
I also noticed that the options work against each-other. How I mean is: 

Only show for tracked quests, will show even if you're not in the zone, even if it's more than 300 yards. 
How I think it should work (again this is completely up to you) Only show if tracked, if that quest is in the zone, if that quest is withing x yards.

**Comment by p3lim** [comment]
> Only show if tracked, if that quest is in the zone, if that quest is withing x yards.

That is how it should work, I don't see how anything else would work with how it's implemented.
It currently checks if it's tracked (or worldquest) first, if so then the zone, if so then the distance.

**Comment by griddark** [comment]
Oh sorry I 100% should have updated here, but my last 3 days have been a bit weird, I'm not sure if my weakauras were messing with this at all, I had a bug that was causing errors to go off super frequently, on like next level I think something like 1k errors in a minute or so... low key it was trying to treat a number like a letter it was crazy enough that weakauras are going to attempt to make it so people can't make that happen by accident. 

Anyway, I have to say everything is working how I think it should, I haven't had any issues while doing world quests or quest the last 24hrs since i fixed that issue. 

Only thing that would help now is if I didn't have to keep setting up the location of the button on every character I log in on. 

thanks again, you have no idea how appreciative I am, been a little humbled by how you just did this.

**Comment by p3lim** [comment]
I found some errors in the order of checks, had to spend a little time trying to make sense of it all, it's been a long day :P

This one should be working:
https://github.com/p3lim-wow/ExtraQuestButton/suites/1428987386/artifacts/24056902

**Comment by p3lim** [comment]
I'll try get profiles working later, you'll have to deal with the inconvenience of positioning for now.
