### ISSUE TITLE
Bug - The button can't be moved

### ISSUE THREAD

**Issue by Sapfirot** [p3lim-wow/ExtraQuestButton#37]
In previous add-ons, the button is moved incorrectly.
I have never seen it work after BFA( the addon was updated

![WoWScrnShot_111220_165727](https://user-images.githubusercontent.com/74363694/98949933-67b85880-2509-11eb-89d6-bf1f90f29ebd.jpg)

**Comment by p3lim** [comment]
The button with the mushroom icon seems to me like it's the Extra**Action**Button, not Extra**Quest**Button, since there are no quest items with that icon in the game.

This addon does not move the Extra**Action**Button.

**Comment by Sapfirot** [comment]
The same problem with quest items - I didn't have time to take a screenshot

**Comment by Sapfirot** [comment]
Previously there was no difference in ExtraActionButton and ExtraQuestButton?

Everything worked thanks to one of your add-ons...

**Comment by p3lim** [comment]
> Previously there was no difference in ExtraActionButton and ExtraQuestButton?

ExtraQuestButton only looks like ExtraActionButton, that's the only similarity. This addon used to move the ExtraActionButton, but maintaining that was a nightmare because other addons also try to move it (e.g. actionbar addons).
