### ISSUE TITLE
Error - perhaps related to party sync

### ISSUE THREAD

**Issue by Tuhljin** [p3lim-wow/ExtraQuestButton#39]
I got this error when the leader of a LFG party I joined enabled party sync (after I accepted the sync). Got the same error again a few seconds after sync, and it might have kept continuing but the party was disbanded at that point.

> 2x ExtraQuestButton\Utils.lua:130: attempt to index local 'info' (a nil value)
> [string "@ExtraQuestButton\Utils.lua"]:130: in function `GetClosestQuestItem'
> [string "@ExtraQuestButton\ExtraQuestButton-90000.21-Release.lua"]:150: in function `callback'
> [string "@ExtraQuestButton\mixins\EventHandlerMixin.lua"]:56: in function <ExtraQuestButton\mixins\EventHandlerMixin.lua:53>
> 
> Locals:
> self = <table> {
>  GenerateItemLinkFromID = <function> defined @ExtraQuestButton\Utils.lua:165
>  mixins = <table> {
>  }
>  Print = <function> defined @ExtraQuestButton\Utils.lua:173
>  GetCurrentMapID = <function> defined @ExtraQuestButton\Utils.lua:169
>  GetClosestQuestItem = <function> defined @ExtraQuestButton\Utils.lua:94
>  db = <table> {
>  }
>  GetNPCID = <function> defined @ExtraQuestButton\Utils.lua:152
>  L = <table> {
>  }
>  GetItemID = <function> defined @ExtraQuestButton\Utils.lua:161
>  itemData = <table> {
>  }
> }
> closestQuestItemLink = nil
> closestDistance = 1000
> onlyInZone = false
> onlyIfWatched = false
> (for index) = 2
> (for limit) = 62
> (for step) = 1
> index = 2
> info = nil
> (*temporary) = nil
> (*temporary) = 2
> (*temporary) = nil
> (*temporary) = "attempt to index local 'info' (a nil value)"
> ns = <table> {
>  GenerateItemLinkFromID = <function> defined @ExtraQuestButton\Utils.lua:165
>  mixins = <table> {
>  }
>  Print = <function> defined @ExtraQuestButton\Utils.lua:173
>  GetCurrentMapID = <function> defined @ExtraQuestButton\Utils.lua:169
>  GetClosestQuestItem = <function> defined @ExtraQuestButton\Utils.lua:94
>  db = <table> {
>  }
>  GetNPCID = <function> defined @ExtraQuestButton\Utils.lua:152
>  L = <table> {
>  }
>  GetItemID = <function> defined @ExtraQuestButton\Utils.lua:161
>  itemData = <table> {
>  }
> }
> GetQuestDistanceWithItem = <function> defined @ExtraQuestButton\Utils.lua:18
>

**Comment by p3lim** [comment]
Fixed in 78c78e3bf95f35859a9dbdf2e5c75f700cdaa7b7.
