### ISSUE TITLE
Uninstalling left the button permanently offset

### ISSUE THREAD

**Issue by jahirahdk** [p3lim-wow/ExtraQuestButton#41]
**Describe the bug**
I installed the addon before realizing that I wouldn't be able to hide the button from view. Upon removing the addon it somehow caused the button to become permanently offset.
I play retail and use Bartender... So far I haven't been able to reset the ExtraActionButton bar without resetting the entire profile - something I'd really like to avoid due to the amount of time spend customizing it.

**How to reproduce**
Tbh, I don't know what happened and there has been no errors to consult. 
The only thing I can safely determine is that the bug didn't occur until the addon was removed... As if it left some kind of a indentation somewhere...

**What did you expect?**
-||-

**Error report**
No errors reported

**Screenshots**
<a href="https://imgur.com/nOsqhAz"><img src="https://i.imgur.com/nOsqhAz.jpg?1" title="source: imgur.com" /></a>

**Comment by p3lim** [comment]
This addon does not move the ExtraActionButton, so there might have been something else that moved it.
I would look under `_retail_/WTF/Account/<youraccountID>/<server>/<character>/layouts-local.txt` and see if the position of ExtraActionButton/Bar has been overridden there.
