### ISSUE TITLE
'Further Gelatinous Research' World Quest wrong position

### ISSUE THREAD

**Issue by catthou** [p3lim-wow/ExtraQuestButton#43]
The EQB for the Further Gelatinous Research world quest (id 61189) in Maldraxxus only shows for the bottom half of the questing area, while most of the slimes you need for it are in the top half.

**Comment by p3lim** [comment]
Feel free to find a better suited "centre" of where the quest should be and give me the coordinates.
You can also adjust the max range from the quest you want the button to show up in the options.

**Comment by p3lim** [comment]
Tested it out, worked fine all the way north within the quest area.
