### ISSUE TITLE
Item suggestions, blacklist non-functional?

### ISSUE THREAD

**Issue by Nulgar** [p3lim-wow/ExtraQuestButton#45]
Started using this addon some weeks ago, loving it, found some more items that should be supported (some you already added in the recent version) - or blacklisted.

**Describe the solution you'd like**
ns.itemData.questItems should be extended by:
- [Discarded Harp](https://www.wowhead.com/item=178464/discarded-harp) for [Go Beyond!](https://www.wowhead.com/quest=60188/go-beyond) (Ardenweald, Night Fae Mushroom Network Daily, item is looted during quest and not shown in questlog, to be used near an NPC - doesn't need to be targetted)
- [Tainted Centurion Component](https://www.wowhead.com/item=174465/tainted-centurion-component) for [The Right Stuff](https://www.wowhead.com/quest=58586/the-right-stuff) (Bastion, Venthyr Campaign)

The ["Call [Construct]" items](https://www.wowhead.com/items/quest/name:call/min-req-level:60/quality:1) from the [weeklies of the Abominable Stitching Necrolord Feature](https://www.wowhead.com/quests/shadowlands/abominable-stitching?filter=28;1;0) need to be addressed. These items are always shown in the quest log, even when the corresponding Abomination is summoned. You don't really "need" these items that often, but they can obstruct items from World Quests, e.g. Call Atticus 'prevents' the use of the skull for the WQ [Deathfang's Favorite Toy](https://www.wowhead.com/quest=61141/deathfangs-favorite-toy) via this addon's button.
Either make them low priority compared to other items, or add them to the blacklist.
**However**. the blacklist is defined in ItemData.lua, but isn't referenced anywhere else in the code, did you maybe delete its use by accident? 
I put a check into GetQuestDistanceWithItem and got the blacklist to work. 

Similarly, the [Ani-Matter Orb](https://www.wowhead.com/item=175827/ani-matter-orb) is used for a [weekly](https://www.wowhead.com/quest=57245/ani-matter-animator) in Maldraxxus, but Necrolords will want to hang onto it to be able to summon the rare Zargox each day.
This orb should also be low priority, as it obstructs the flag for [Parts to a Whole](https://www.wowhead.com/quest=58437/parts-to-a-whole).

Regarding the "low priority during collision" categories in ItemData.lua, it seems this only applies to the category checks for an item, not vs. other quest items. Maybe an option to always prefer World Quests? They're usually your top priority. This would be another way to address the above Necrolord items.
(Hope this still makes sense, only realized the stuff in the last paragraph while writing this, so I shifted sentences and words around a lot)

**Comment by p3lim** [comment]
Thanks for the suggestions.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/ExtraQuestButton/commit/d69cbe7bdbe7136e546c6beb0702ef5809c00a7b

**Comment by p3lim** [comment]
Feel free to try out this alpha version:
https://github.com/p3lim-wow/ExtraQuestButton/suites/3137211553/artifacts/72013085

**Comment by Nulgar** [comment]
Sorry for the late reply, couldn't get around to check it out due to family stuff and bad short-term memory ;) aaaand then lost a longer reply to the first bluescreen in ages :O

But, uh, are you sure the change in [d69cbe7](https://github.com/p3lim-wow/ExtraQuestButton/commit/d69cbe7bdbe7136e546c6beb0702ef5809c00a7b) actually makes a difference? If closestQuestItemLink is set, the following ifs are skipped anyway. It still means that only supertracked world quests found in the first loop are preferred.

A "cosmetic" mistake: the entry for [The Right Stuff](https://www.wowhead.com/quest=58586/the-right-stuff) says "Kyrian Covenant" - while the quest takes place in Bastion, it's part of the **Venthyr** Campaign ;)

Also noticed you don't have localization data yet, here's deDE from a native speaker:
```
L['Only show for tracked quests'] = 'Nur für verfolgte Quests anzeigen'
L['Only show for quests in current zone'] = 'Nur für Quests in der aktuellen Zone anzeigen'
L['Distance in yards how far away the quest can be'] = 'Maximaler Abstand zur Quest in m'
L['Prefer to show button for world quests'] = 'Button für Weltquests bevorzugt anzeigen'
```
