### ISSUE TITLE
Error occurring when zoning into a Cataclysm dungeon.

### ISSUE THREAD

**Issue by Ookami313** [p3lim-wow/ExtraQuestButton#47]
Queued up to run some Cataclysm Timewalking on my Demon Hunter. Upon zoning into a dungeon I received the following error. Thanks.

12x Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken)
[string "=[C]"]: in function `GetPlayerMapPosition'
[string "@ExtraQuestButton\Utils.lua"]:9: in function <ExtraQuestButton\Utils.lua:7>
[string "@ExtraQuestButton\Utils.lua"]:73: in function <ExtraQuestButton\Utils.lua:18>
[string "@ExtraQuestButton\Utils.lua"]:152: in function `GetClosestQuestItem'
[string "@ExtraQuestButton\ExtraQuestButton-90100.24-Release.lua"]:158: in function `callback'
[string "@ExtraQuestButton\mixins\EventHandlerMixin.lua"]:56: in function <ExtraQuestButton\mixins\EventHandlerMixin.lua:53>

Locals:
(*temporary) = "Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken)"

**Comment by p3lim** [comment]
Thanks for the report, I'll take a look into it.

**Comment by p3lim** [comment]
Since this is map-specific, which dungeon did you encounter this error in?

**Comment by Ookami313** [comment]
Oof, It was multiple times and I can't remember the specific ones off the top of my head. I do remember running Stonecore, Throne of Tides, Lost City of Tol'vir, the Vortex Pinacle, and Grim Batol. I'm going to run another alt, so this time I'll take note and post if the full list doesn't help.

**Comment by Ookami313** [comment]
Just ran Grim Batol, End Time, and Vortex Pinnacle. No issues with those.

**Comment by p3lim** [comment]
Did you happen to have any of these quests in your log when you encountered the error?

https://www.wowhead.com/quest=12484
https://www.wowhead.com/quest=35001
https://www.wowhead.com/quest=27389
https://www.wowhead.com/quest=27451
https://www.wowhead.com/quest=57455
https://www.wowhead.com/quest=63971

**Comment by Ookami313** [comment]
Snail Stomping is possible, I was working on my weekly invasion on that character I believe. The others I have not done recently on my Demon Hunter.
Also, Just ran Lost City of Tol'vir with no issue, but finished my 5 on this alt (Hunter) with no Stonecore run. I know at least 2 errors went off with multiple hits each (x12), so it may have been character specific for my DH. Thanks.
