### ISSUE TITLE
More special cases

### ISSUE THREAD

**Issue by Nulgar** [p3lim-wow/ExtraQuestButton#49]
During the WQ [Drawing Out the Poison](https://www.wowhead.com/quest=61708/drawing-out-the-poison) you loot the [Phylactery of Arin'gore](https://www.wowhead.com/item=174043/phylactery-of-aringore), which you need to use to summon the target mob. Simple **questItems** addition.

The Korthia/Archivists' Codex quest [Diviner's Rune Chits](https://www.wowhead.com/quest=63892/diviners-rune-chits) has you randomly loot [Diviner's Rune Chit](https://www.wowhead.com/item=185963/diviners-rune-chit)s from treasures in Korthia, which have to be used to gain actual quest progress, and thus aren't displayed in the quest tracker for EQB to pick up on automatically. 
(Similar to _BfA's_ [The Great Sea Scrolls](https://www.wowhead.com/quest=53476/the-great-sea-scrolls) / [Tortollan Pilgrimage Scroll](https://www.wowhead.com/item=163852/tortollan-pilgrimage-scroll)s, in fact)
I added this to the **questItems** section in my local copy, and also had to add it to **inaccurateQuestAreas**, since the quest itself has no defined quest area. I suggest the areas `{ 1961, 2006, 2007 }` for Korthia and its two caves with their own map, although given the nature of the quest, a simple `true` would also fit, you'd want to use the items as soon as possible anyway, and you only loot them in Korthia... but let's not get too philosophical, I'll leave the decision to your opinion.

I noticed you added the items for [Who Devours the Devourers?](https://www.wowhead.com/quest=60609/who-devours-the-devourers), but Lua ignores the first entry for the green item (other languages would complain about using an array index/key twice)
You'd have to use a table to store both itemIDs under the same questID index, and then account for that in the determining function, use the first item from the table that you possess (priority on the blue item, in this case)

**PS:** While this ticket is still open, a thing I found while levelling:
[Boom Boots](https://www.wowhead.com/item=57412/boom-boots) (for both H/A versions of [A Breath of Fresh Air](https://www.wowhead.com/search?q=A+Breath+of+Fresh+Air)) need an entry in **completeItems**, as the quest is 'complete' on accept. UiMapID is 205, Shimmering Expanse (although the code currently just looks for a non-false value in the array)

**Comment by p3lim** [comment]
I'll take a look at this once I have an active subscription again, which will probably be 9.2.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/ExtraQuestButton/commit/148d9a2b4062110ab03cd933c1c9631cfb748289
https://github.com/p3lim-wow/ExtraQuestButton/commit/a94f377bb5842f0d1e42e87dd8edef55323ff1dc
https://github.com/p3lim-wow/ExtraQuestButton/commit/28080aa80f6f3ffd9b49ce8b80ea4c4d4c7f89a4
