### ISSUE TITLE
Midsummer Fire Festival - Torch Tossing and Catching Quests

### ISSUE THREAD

**Issue by Dairyman** [p3lim-wow/ExtraQuestButton#5]
This quests have missing area blobs: 
Torch Tossing: 11921, 11922, 11926, 11731
Torch Catching: 11923, 11924, 11925, 11657

Version: 60100.4-Beta

**Comment by p3lim** [comment]
5502a323b59664d3fecb9a3ecf22e6f2ab92fc3a
