### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by linaori** [p3lim-wow/ExtraQuestButton#50]
**Describe the bug**
EQB memory usage grows at a linear rate. It starts at <1mb and gradually goes up. Earlier I had it on 10MB+. 

**How to reproduce**
Just having it enabled seems to cause it

**What did you expect?**
A more consistent memory usage

**Error report**
n/a

**Screenshots**
https://user-images.githubusercontent.com/1754678/143659892-6e106a11-a75c-4e56-9937-f95d685adc5a.mp4

**Comment by linaori** [comment]
After doing some digging, I've traced the memory increase to this line, and I can't seem to figure out what's causing it. There doesn't seem to be anything wrong in this code from what I can tell, will do more digging later.

https://github.com/p3lim-wow/ExtraQuestButton/blob/28cbf2b5687173476e45c89ab7b61c22103b01a8/Utils.lua#L159

**Comment by p3lim** [comment]
It's an API that is being basically polled, not just by this addon, but by the default interface and multiple other addons.

There is no good way of dealing with this, and while I could add some form of caching around the quest log it wouldn't be of any great benefit.

It's up to Blizzard to either change how the API works, how often it needs to be called to get this type of information, or just improve it as-is.
