### ISSUE TITLE
Wago upload

### ISSUE THREAD

**Issue by janpantel** [p3lim-wow/ExtraQuestButton#52]
Hey, we've just seen that you experienced issues uploading your addon. We just fixed a bug that prevented you from doing it :-) please try again. In case you need further help feel free to reach out on Discord: `Jayow#8905`

**Comment by p3lim** [comment]
@janpantel Upload worked, but I'm unable to update any settings on it, just getting an error saying "The slug has already been taken".

Your privacy settings on Discord is preventing me from sending you a message :smiley:.

**Comment by janpantel** [comment]
That's weird, it tells me the same when I try to message/add you :-S have you tried adding me as a friend?

**Comment by p3lim** [comment]
Done.

**Comment by p3lim** [comment]
Resolved on discord.
