### ISSUE TITLE
Custom key binds not working

### ISSUE THREAD

**Issue by Billtopia** [p3lim-wow/ExtraQuestButton#54]
So, in order for the key binds to work right you will need to change either the Binding.xml (all instances) EXTRAQUESTBUTTON to ExtraQuestButton
or in ExtraQuestButton.lua   in function ExtraQuestButton:UpdateBinding()  local keyButton = addonName  to local keyButton = string.upper(addonName)

 

It has the key binding registered as EXTRAQUESTBUTTON (in the xml) and tries to look it up as ExtraQuestButton (in the lua)

**Comment by p3lim** [comment]
Thanks for the detailed report.

**Comment by p3lim** [comment]
I went with the latter option, as changing the binding name would reset the binding for players.
