### ISSUE TITLE
Missing Quest Item

### ISSUE THREAD

**Issue by Artifcer** [p3lim-wow/ExtraQuestButton#58]
Ley Line Focus Control Ring - ItemID "36751"

Quest - "The Focus on the Beach"  QuestID - "12065"

Location - Northrend > Dragonblight > 26.5, 65.5

![image](https://user-images.githubusercontent.com/108841021/177658772-e0cb7f6b-40b8-4308-aa23-c2b0ab9adfc0.png)

![image](https://user-images.githubusercontent.com/108841021/177658834-fa07a8d6-e270-4e26-b173-e2ee365e5534.png)

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/ExtraQuestButton/commit/c7902d56601125d1ecd3dff67ed0528e9128a288
