### ISSUE TITLE
Dragonflight Beta: Error on logon

### ISSUE THREAD

**Issue by sebid** [p3lim-wow/ExtraQuestButton#60]
**Describe the bug**

Addon is installed ([90200.29-Release](https://www.curseforge.com/wow/addons/extraquestbutton/files/3668915)) and Beta client is loaded.

**How to reproduce**

Load into world.

**What did you expect?**

Addon to be initialized.

**Error report**

```
Message: Interface/AddOns/ExtraQuestButton/config/Options.lua:58: attempt to index global 'InterfaceOptionsFrameAddOns' (a nil value)
Time: Sun Sep  4 12:17:19 2022
Count: 1
Stack: Interface/AddOns/ExtraQuestButton/config/Options.lua:58: attempt to index global 'InterfaceOptionsFrameAddOns' (a nil value)
[string "@Interface/AddOns/ExtraQuestButton/config/Options.lua"]:58: in main chunk

Locals: addonName = "ExtraQuestButton"
ns = <table> {
 GenerateItemLinkFromID = <function> defined @Interface/AddOns/ExtraQuestButton/Utils.lua:191
 GetClosestQuestItem = <function> defined @Interface/AddOns/ExtraQuestButton/Utils.lua:124
 itemData = <table> {
 }
 mixins = <table> {
 }
 L = <table> {
 }
 Print = <function> defined @Interface/AddOns/ExtraQuestButton/Utils.lua:195
 GetNPCID = <function> defined @Interface/AddOns/ExtraQuestButton/Utils.lua:182
}
L = <table> {
}
CreateOptions = <function> defined @Interface/AddOns/ExtraQuestButton/config/Options.lua:4
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'InterfaceOptionsFrameAddOns' (a nil value)"

```

**Screenshots**

**Comment by p3lim** [comment]
Pretty much every addon that exists is going to be broken when a new expansion comes, there is no point opening an issue for this, especially when there's only been 2 days since addons were enabled with months until a release. Don't be that guy.

**Comment by sebid** [comment]
@p3lim

The same error occurs on Dragonflight pre-patch. Would a new issue be feasible or can this one be reopened?
`Message: Interface/AddOns/ExtraQuestButton/config/Options.lua:58: attempt to index global 'InterfaceOptionsFrameAddOns' (a nil value)
Time: Fri Oct 28 16:42:54 2022
Count: 1
Stack: Interface/AddOns/ExtraQuestButton/config/Options.lua:58: attempt to index global 'InterfaceOptionsFrameAddOns' (a nil value)
[string "@Interface/AddOns/ExtraQuestButton/config/Options.lua"]:58: in main chunk

Locals: addonName = "ExtraQuestButton"
ns = <table> {
 GenerateItemLinkFromID = <function> defined @Interface/AddOns/ExtraQuestButton/Utils.lua:191
 GetClosestQuestItem = <function> defined @Interface/AddOns/ExtraQuestButton/Utils.lua:124
 itemData = <table> {
 }
 mixins = <table> {
 }
 L = <table> {
 }
 Print = <function> defined @Interface/AddOns/ExtraQuestButton/Utils.lua:195
 GetNPCID = <function> defined @Interface/AddOns/ExtraQuestButton/Utils.lua:182
}
L = <table> {
}
CreateOptions = <function> defined @Interface/AddOns/ExtraQuestButton/config/Options.lua:4
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'InterfaceOptionsFrameAddOns' (a nil value)"
`
