### ISSUE TITLE
Missing Quest: Never Forgotten

### ISSUE THREAD

**Issue by raysmith59** [p3lim-wow/ExtraQuestButton#68]
Part of the Evoker starting questline, there's a quest item Toxin Antidote that doesn't show up in the frame.

**Comment by raysmith59** [comment]
Never mind, it did show up briefly as I approached the quest area but once I entered the poison area the button moved to the Extra Abilities frame.  A bit odd and I think I'd want the EQB frame to show the quest item while it's the actively tracked quest even outside of the immediate area.  Closing since not really an enhancement, though.

**Comment by p3lim** [comment]
I'm considering adding it to the block list because it's one of those times where blizzard is doing what I'm trying to do with this addon, similar to the 3 items in WoD that got me started on this in the first place.
