### ISSUE TITLE
Quest item for Flying Fish not automatically activating EQB

### ISSUE THREAD

**Issue by raysmith59** [p3lim-wow/ExtraQuestButton#69]
This may be specific to my scenario, I don't think this was an issue before I got Harpoon.  I'm also only Tuskarr rank 6 which means I shouldn't *have* Harpoon yet.  It's confusing, but I think even if this is a game but-related issue it might point to a broader issue where if the Extra Abilities game UI element is active, EQB won't show.  Meh, I don't know.

I'm in a fishing area in Waking Shores (63, 76), the Harpoon action button is active in the Extra Abilities section but EQB is (correctly) currently unused.  When I pick up the quest Flying Fish it should enable EQB with the Throw Net button, but it doesn't.  However, if I go into and back out of edit mode, the EQB button shows up at that point.

**Comment by raysmith59** [comment]
Looks like Harpoon isn't the Tuskarr rep Harpoon, it's a world quest Harpoon.  This expansion is confusing.  So nothing's really changed except the Extra Abilities button is legit and EQB isn't showing up without going into and out of edit mode.

**Comment by p3lim** [comment]
If there isn't a keybind for EQB separate from EAB then EAB gets priority, which should be what's happening here.
