### ISSUE TITLE
2 Separate Bindings Issues 

### ISSUE THREAD

**Issue by xOFrankNFurterOx** [p3lim-wow/ExtraQuestButton#71]
**Describe the bug**
1. Bindings from ExtraActionButton1 are not properly moving over to the EQB and when you hit them they dont activate the EQB button.

2. When you have multiple quests 1 that uses a "quest item" and 1 that uses a fake world item like the Fishing Net which is an item in your inventory -> and the Harpoon / Pull Hard which are virtual things that just show up when you are in a certain area, you do not show bindings on the latter, and the bindings that are setup don't work.

**Comment by p3lim** [comment]
Assuming this is related to #69, let me know if it doesn't accurately match its description.
