### ISSUE TITLE
Translation: 

### ISSUE THREAD

**Issue by BlueNightSky** [p3lim-wow/ExtraQuestButton#80]
### Which locale are these translations for?

zhTW (Chinese, Traditional, Taiwan)

### "Button scale"

按鈕大小

### "Artwork opacity"

美術透明度

### "Artwork style"

美術樣式

### "Hide cooldown text"

隱藏冷卻文字

### "Only show for tracked quests"

只顯示已追蹤任務

### "Only show for quests in current zone"

只顯示當前區域任務

### "Tracking distance"

追蹤距離

**Comment by p3lim** [comment]
Thanks!
