### ISSUE TITLE
Make this Addon ElvUI compatible please :)

### ISSUE THREAD

**Issue by Rubyurek** [p3lim-wow/ExtraQuestButton#86]
**Describe the solution you'd like**
Make the addon compatible with ElvUI. It looks strange when the addon uses the BlizzUI elements although my whole UI screams for ElvUI.

**Describe alternatives you've considered**
---

![addon](https://github.com/p3lim-wow/ExtraQuestButton/assets/42946288/d8e929f6-9264-4c20-a899-6e3af3573f71)

**Comment by p3lim** [comment]
It supports Masque.
