### ISSUE TITLE
Mixin error in pools.lua

### ISSUE THREAD

**Issue by ms411** [p3lim-wow/ExtraQuestButton#93]
**Describe the bug**
This error presents when logging in after the War Within Prepatch 11.0

**How to reproduce**
Load the game with version 11.0 and addon version 110000.49-Release

**What did you expect?**
No error

**Error report**

```
1x Blizzard_SharedXMLBase/Mixin.lua:9: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/Mixin.lua"]:9: in function <Blizzard_SharedXMLBase/Mixin.lua:6>
[string "=(tail call)"]: ?
[string "@ExtraQuestButton/libs/LibEditMode-7/pools.lua"]:8: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

```

**Screenshots**

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/ExtraQuestButton/commit/f557541c65295618eafc38d9a8a8a7713d534199
