### ISSUE TITLE
Translation:

### ISSUE THREAD

**Issue by Tsundoro** [p3lim-wow/ExtraQuestButton#97]
### Which locale are these translations for?

zhCN (Chinese, Simplified, PRC)

### "Button scale"

按钮缩放

### "Artwork opacity"

外观透明度

### "Artwork style"

外观样式

### "Hide cooldown text"

隐藏冷却文字

### "Only show for tracked quests"

只显示已追踪的任务

### "Only show for quests in current zone"

只显示所在地区的任务

### "Tracking distance"

追踪距离

**Comment by p3lim** [comment]
Thanks!
